---
- name: Update APT package index
  hosts: all
  become: yes  # Use sudo to run the task
  tasks:
    - name: Run apt-get update
      apt:
        update_cache: yes  # Equivalent to 'apt-get update'
        cache_valid_time: 3600  # Only update if the cache is older than 1 hour
