---
- name: Update APT package index on Debian server using su to root and reboot
  hosts: all
  become: yes
  become_method: su  # Use 'su' to switch to root
  become_user: root  # Become the root user
  tasks:
    - name: Run apt-get update as root
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Reboot the server after update
      reboot:
        msg: "Rebooting after apt-get update"
        reboot_timeout: 600
        connect_timeout: 5  # Time before retrying connection after reboot

    - name: Wait for the server to come back up
      wait_for:
        port: 22
        timeout: 300  # Wait for SSH to be available

    - name: Display system uptime
      command: uptime
      register: uptime_output

    - name: Print uptime on console
      debug:
        msg: "Uptime: {{ uptime_output.stdout }}"
