---
- name: Reboot Ubuntu system
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Reboot the system
      ansible.builtin.reboot:
        reboot_timeout: 30
      ignore_errors: true
