---
- name: Reboot machine
  hosts: all
  become: true

 - name: Reboot machine using a custom reboot command
   ansible.builtin.reboot:
    reboot_command: launchctl reboot userspace
    boot_time_command: uptime | cut -d ' ' -f 5
