---
- name: Update Debian server
  hosts: all
  become: yes  # Use sudo for tasks that require elevated privileges
  tasks:

    - name: Update the APT package index
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Install security updates
      apt:
        upgrade: dist
        cache_valid_time: 3600  # Refresh cache if it's older than 1 hour

    - name: Remove unnecessary packages and dependencies
      apt:
        autoremove: yes
        autoclean: yes

    - name: Reboot the server if required
      reboot:
        msg: "Reboot initiated by Ansible after system update"
        reboot_timeout: 600
        connect_timeout: 300
