---
- name: Update APT package index on Debian server using su to root
  hosts: all
  become: yes
  become_method: su  # Use 'su' to switch to root
  become_user: root  # Become the root user
  tasks:
    - name: Run apt-get update as root
      apt:
        update_cache: yes
        cache_valid_time: 3600

- name: Reboot the server after update
      reboot:
        msg: "Rebooting after apt-get update"
        reboot_timeout: 600
