---
- name: Update Debian server
  hosts: all
  become: yes  # Use sudo for elevated privileges
  tasks:

    - name: Update the APT package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Remove unnecessary packages
      apt:
        autoremove: yes
        autoclean: yes

    - name: Reboot the server if needed
      reboot:
        msg: "Rebooting after updates"
        reboot_timeout: 600
